apiVersion: v1
kind: Secret
metadata:
  name: express-ts-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://dev:dev@postgres:5432/expressts?schema=public"
  ACCESS_TOKEN_SECRET: "my_access_token_secret"
  REFRESH_TOKEN_SECRET: "my_refresh_token_secret"
  SESSION_TOKEN_SECRET: "my_session_token_secret"
